version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.20.2
      - run:
          name: Debug DATABASE_URL_TEST
          command: echo "DATABASE_URL_TEST=${DATABASE_URL_TEST}"
    environment:
      DATABASE_URL: ${DATABASE_URL_TEST}
    steps:
      - checkout
      
      - run:
          name: Set up environment file
          command: |
            echo "DATABASE_URL=${DATABASE_URL_TEST}" > .env.local

      - node/install-packages

      - run:
          name: Prisma DB Push
          command: |
            export DATABASE_URL=${DATABASE_URL_TEST}
            npx prisma db push

      - run:
          name: Create 2dsphere index on geo
          command: node scripts/create-2dsphere-index.js

      - run:
          name: Run tests
          command: npm run test

  cypress-tests:
    docker:
      - image: cypress/included:13.9.0 
    steps:
      - checkout

      - run:
          name: Set up environment file
          command: |
            echo "DATABASE_URL=${DATABASE_URL_TEST}" > .env.local

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Start App + Run Cypress
          command: |
            npm run dev:test &
            npx wait-on http://localhost:3000
            npx cypress run

  notify-github:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Notify GitHub if tests pass
          command: |
            curl -X POST https://api.github.com/repos/PaulineFranck98/next-cda-project/dispatches \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GH_PAT" \
              -d '{"event_type":"trigger-merge-to-test"}'

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: develop
      - cypress-tests:
          requires:
            - build-and-test
      - notify-github:
          requires:
            - build-and-test
            - cypress-tests