# version: 2.1

# orbs:
#   node: circleci/node@5.1.1

# jobs:
#   build-and-test:
#     docker:
#       - image: cimg/node:18.20.2
#     steps:
#       - checkout

#       - run:
#           name: Set up environment file
#           command: |
#             echo "DATABASE_URL=${DATABASE_URL_TEST}" > .env.local

#       - node/install-packages

#       - run:
#           name: Run tests
#           command: npm run test

#   cypress-tests:
#     docker:
#       - image: cypress/included:13.9.0 
#     steps:
#       - checkout

#       - run:
#           name: Set up environment file
#           command: |
#             echo "DATABASE_URL=${DATABASE_URL_TEST}" > .env.local

#       - run:
#           name: Install Dependencies
#           command: npm ci

#       - run:
#           name: Start App + Run Cypress
#           command: |
#             npm run dev:test &
#             npx wait-on http://localhost:3000
#             npx cypress run

#   trigger-merge-to-test:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - run:
#           name: Trigger merge-develop-to-test GitHub Action
#           command: |
#             curl -X POST https://api.github.com/repos/PaulineFranck98/next-cda-project/dispatches \
#               -H "Accept: application/vnd.github.v3+json" \
#               -H "Authorization: token $GH_PAT" \
#               -d '{"event_type":"trigger-merge-to-test"}'

# workflows:
#   build-and-test:
#     jobs:
#       - build-and-test:
#           filters:
#             branches:
#               only: develop
#       - cypress-tests:
#           requires:
#             - build-and-test
#       - trigger-merge-to-test:
#           requires:
#             - build-and-test
#             - cypress-tests

version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout

      - run:
          name: Set up environment file
          command: |
            echo "DATABASE_URL=${DATABASE_URL_TEST}" > .env.local

      - node/install-packages

      - run:
          name: Run tests
          command: npm run test

  cypress-tests:
    docker:
      - image: cypress/included:13.9.0 
    steps:
      - checkout

      - run:
          name: Set up environment file
          command: |
            echo "DATABASE_URL=${DATABASE_URL_TEST}" > .env.local

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Start App + Run Cypress
          command: |
            npm run dev:test &
            npx wait-on http://localhost:3000
            npx cypress run

  notify-github:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Notify GitHub if tests pass
          command: |
            curl -X POST https://api.github.com/repos/PaulineFranck98/next-cda-project/dispatches \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GH_PAT" \
              -d '{"event_type":"trigger-merge-to-test"}'

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: develop
      - cypress-tests:
          requires:
            - build-and-test
      - notify-github:
          requires:
            - build-and-test
            - cypress-tests