import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Loading from "@/components/Loading";
import { SignedIn, SignedOut, SignOutButton } from '@clerk/nextjs'


const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-nunito'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>)  {  

  return (
    <ClerkProvider afterSignOutUrl='/'>
      <html lang="fr">
        <body
          className={`${nunito.className} antialiased`}
        >
          <Loading/>
          <header className="flex gap-2">
            <SignedOut>
              <a href='/sign-up'><p>Sign up</p></a>
              <a href='/sign-in'><p>Sign in</p></a>
            </SignedOut>
            <SignedIn>
              <p>Hello</p>
              <SignOutButton />
            </SignedIn>
          </header>
          <main>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
