import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Loading from "@/components/Loading";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'], 
//   display: 'swap',
//   variable: '--font-poppins'
// });


const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choisis les poids que tu veux utiliser
  display: 'swap',
  variable: '--font-nunito'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl='/'>
      <html lang="fr">
        <body
          className={`${nunito.className} antialiased`}
        >
          <Loading/>
          <header>
            <a href='/sign-up'><p>Sign up</p></a>
            <a href='/sign-in'><p>Sign in</p></a>
          </header>
          <main>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
