import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import "./globals.css";
// import Link from "next/link";
import { LoadingProvider } from "@/context/LoadingContext";
import Loading from "@/components/Loading";
import { SignedOut } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/providers/theme-provider";
import { frFR } from '@clerk/localizations'
import Link from "next/link";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	display: 'swap',
	variable: '--font-nunito'
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

	return (
		<html lang="fr" suppressHydrationWarning>
			<body
				className={`${poppins.className} antialiased`}
			>
				<ClerkProvider localization={frFR} afterSignOutUrl='/'>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
						<LoadingProvider>
							<Loading />
							<SignedOut>
								<header className="flex gap-6 border-b border-b-gray-200 py-2 px-4 font-semibold">
									<Link href='/sign-up' className="text-violet-800 "><p>Inscription</p></Link>
									<Link href='/sign-in' className="text-violet-800"><p>Connexion</p></Link>
								</header>
							</SignedOut>
							<main>
								<Toaster position="top-center" />
								{children}
							</main>
						</LoadingProvider>
					</ThemeProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
