name: Create PR test to main
 
on:
  repository_dispatch:
    types: [trigger-pr-to-main]
 
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: test
          title: "PR automatique : test → master"
          body: "Tests E2E validés sur test"