name: Auto Merge develop into test

on:
  repository_dispatch:
    types: [trigger-merge]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          ref: test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Merge develop into test
        run: |
          git merge develop --allow-unrelated-histories --no-ff -m "Auto-merge develop into test [skip ci]"
          git push origin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}